version: '3.7'

services:
  postgres:
    image: postgres:alpine
    hostname: postgres
    environment:
      - POSTGRES_DB=local
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
