spring.application.name:
  backend
jpa:
  database-platform: org.hibernate.dialect.PostgreSQLDialect
datasource:
  url: ${SERVICE_TEMPLATE_DBPOSTGRESS_HOST:jdbc:postgresql://localhost:5432/local}
  username: ${SERVICE_TEMPLATE_DBPOSTGRESS_USERNAME:postgres}
  password: ${SERVICE_TEMPLATE_DBPOSTGRESS_PASSWORD:postgres}
