spring:
  application:
    name: backend
  datasource:
    database: local
    url: jdbc:postgresql://localhost:5432/local
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      continue-on-error: true
      mode: always
    schema-locations: classpath:/import.sql
  jackson:
    serialization:
      fail-on-empty-beans: false
external-services:
    url: http://localhost:9090
